### ISSUE TITLE
Add documentation about Linux

### ISSUE THREAD

**Issue by b-studios** [effekt-lang/effekt-website#1]
Currently linux users have to use `effekt.sh` instead of `effekt`. This needs to be documented.

Also see https://github.com/effekt-lang/effekt/issues/16

**Comment by jiribenes** [comment]
Seems to be done now:
<img width="1357" alt="Screenshot 2024-09-10 at 13 32 51" src="https://github.com/user-attachments/assets/3397eab4-eeb4-48c3-a91a-a8583f69ae64">
https://effekt-lang.org/docs/getting-started#effekt-on-linux

**Comment by jiribenes** [comment]
Just noticed the typo in `effe*c*t.sh`; fixed in https://github.com/effekt-lang/effekt-website/commit/5bd1e7ed8b23d0ff5ef47a1c91b7afad9abbdbfa.
