### ISSUE TITLE
Compilation errors for interactive code snippets using Console

### ISSUE THREAD

**Issue by marvinborner** [effekt-lang/effekt-website#38]
Two interactive code snippets error on execution with "Could not resolve type Console"

- https://github.com/effekt-lang/effekt-website/blob/26493b1a1063dea79c33df9f3e45be789118c37c/docs/concepts/effect-handlers.md?plain=1#L84-L86
- https://github.com/effekt-lang/effekt-website/blob/26493b1a1063dea79c33df9f3e45be789118c37c/docs/concepts/effect-handlers.md?plain=1#L171-L173

**Comment by jiribenes** [comment]
Seems to be resolved in the current version on `master`.
