### ISSUE TITLE
Port introduction to first-class values and boxing

### ISSUE THREAD

**Issue by b-studios** [effekt-lang/effekt-website#58]
We had some explanations on System C, that would be nice to be ported / used as inspiration for the effekt-lang website:

https://se-tuebingen.github.io/oopsla-2022-artifact/tutorial/

**Comment by jiribenes** [comment]
Being ported as part of https://github.com/effekt-lang/effekt/pull/536 and https://github.com/effekt-lang/effekt/issues/571.

**Comment by jiribenes** [comment]
Ported as part of the Tour + the Scheduler case study.
